services:
  - type: web
    name: jarvisx-web
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn main:app --bind 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
