services:
  - type: web
    name: jarvisx-web
    env: python
    buildCommand: ""
    startCommand: "gunicorn main:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true
